const $=x=>document.getElementById(x),K="alarms_fixed_v1";let A=JSON.parse(localStorage.getItem(K)||"[]"),edit=null;
function save(){localStorage.setItem(K,JSON.stringify(A));render()}function fmt(t){let [h,m]=t.split(":").map(Number),d=new Date();d.setHours(h,m);return d.toLocaleTimeString([],{hour:"numeric",minute:"2-digit"})}
function allowed(r){let d=new Date().getDay();return r=="daily"||r=="once"||(r=="weekdays"&&d>0&&d<6)||(r=="weekends"&&(d==0||d==6))}
function render(){ $("count").textContent=A.length+" alarm"+(A.length!=1?"s":"");$("empty").style.display=A.length?"none":"block";$("list").innerHTML=A.map((a,i)=>`<div class="alarm"><div class="main"><div class="alarmtime">${fmt(a.time)}</div><div class="meta">${a.repeat} • ${a.label||"Alarm"}</div></div><div class="actions"><button onclick="editA(${i})">✎</button><button class="del" onclick="delA(${i})">×</button><button onclick="toggleA(${i})">${a.on?"ON":"OFF"}</button></div></div>`).join("")}
function editA(i){edit=i;$("at").value=A[i].time;$("label").value=A[i].label;$("repeat").value=A[i].repeat;$("dlg").showModal()}
function delA(i){if(confirm("Delete this alarm?")){A.splice(i,1);save()}}function toggleA(i){A[i].on=!A[i].on;save()}
$("add").onclick=()=>{edit=null;$("form").reset();$("dlg").showModal()};$("cancel").onclick=()=>$("dlg").close();
$("form").onsubmit=e=>{e.preventDefault();let x={time:$("at").value,label:$("label").value,repeat:$("repeat").value,on:true,last:""};if(edit===null)A.push(x);else A[edit]=x;save();$("dlg").close()};
function tick(){let d=new Date(),h=d.getHours(),m=String(d.getMinutes()).padStart(2,"0"),s=String(d.getSeconds()).padStart(2,"0"),hm=String(h).padStart(2,"0")+":"+m;$("time").textContent=String(h%12||12).padStart(2,"0")+":"+m;$("sec").textContent=s;$("ampm").textContent=h>=12?"PM":"AM";$("date").textContent=d.toLocaleDateString([],{weekday:"long",month:"long",day:"numeric",year:"numeric"});$("greeting").textContent=h<12?"morning":h<18?"afternoon":"evening";if(s=="00")A.forEach((a,i)=>{let key=d.toDateString()+hm;if(a.on&&a.time==hm&&allowed(a.repeat)&&a.last!=key){a.last=key;if(a.repeat=="once")a.on=false;save();ring(a)}})}
function ring(a){$("rt").textContent=fmt(a.time);$("rl").textContent=a.label||"Alarm";$("ring").hidden=false;$("audio").currentTime=0;$("audio").play().catch(()=>{})}
$("stop").onclick=()=>{ $("audio").pause();$("ring").hidden=true};$("snooze").onclick=()=>{let d=new Date(Date.now()+300000);A.push({time:d.toTimeString().slice(0,5),label:"Snooze",repeat:"once",on:true,last:""});save();$("audio").pause();$("ring").hidden=true};
$("theme").onclick=()=>{document.body.classList.toggle("dark");$("theme").textContent=document.body.classList.contains("dark")?"☀":"☾"};$("ring").hidden=true;if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{});render();tick();setInterval(tick,1000);